server:
  port: 8082
spring:
  config:
    activate:
      on-profile: dev
  application:
    name: email-sender
  mail:
    host: smtp.gmail.com
    port: 587
    username: uranovrg@gmail.com
    password: przi jnrn osmd klbw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
